### ISSUE TITLE
Add front-matter to controls/_index.md

### ISSUE THREAD

**Issue by einari** [dolittle-interaction/JavaScript.Components.Aurelia#22]
Front mater is missing from `controls/_index.md, and as a result the menu item is "missing".

Add relevant front matter, without any content for the section to appear in the menu.

ref:
﹍https://github.com/dolittle-interaction/JavaScript.Components.Aurelia/blob/master/Documentation/controls/_index.md﹍

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1128716991508776)
┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1128717137519122">image.png</a>

**Comment by Virrum** [comment]
It's fixed in my task "in progress".

**Comment by pavsaund** [comment]
Ah, great! Fastest fix ever 👍
